### ISSUE TITLE
npm package out of date

### ISSUE THREAD

**Issue by isao** [rsms/js-lru#31]
I have the latest version from npm `"lru_map": "^0.3.3"` which I would expect to contain recent bug fixes.  

But the actual `node_modules/lru-cache/lib/lru-cache.js` file modification date is Nov 25, 2015 for the npm installed package. The source is missing bug fixes from 2016.

Can you please `npm pub` again from HEAD?

Thanks!

**Comment by isao** [comment]
Note, a workaround is specifying the following in package.json:

        "lru_map": "git@github.com:rsms/js-lru.git#427fd5dde56ac1cf5ba14511d4a4daa47bdb21ce"

**Comment by isao** [comment]
Hm, apologies. This seems like my mistake.

**Comment by rsms** [comment]
AFAIK timestamps are not updated when archives for NPM are produced, and your unarchiver seems to do the correct thing and also not update the mtime and ctime of the files after extracting, thus the odd modification dates.

**Comment by isao** [comment]
My mistake! The npm version 0.3.3 is the same as git HEAD.

I ran into bug #14, and was confused because I had just bundled the latest from npm. Turns out there was a copy of a fork of LRUMap elsewhere in the codebase(!).

**Comment by isao** [comment]
BTW thanks for publishing and maintaining this package :)
